version: '3.8'

services:
  app:
      build: .
      container_name: Royalstore_app
      working_dir: /var/www
      volumes:
        - ./:/var/www
      environment:
        - COMPOSER_ALLOW_SUPERUSER=1

  webserver:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  node:
    image: node:20
    container_name: nodejs
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/docker-entrypoint.sh:/docker-entrypoint.sh
    entrypoint: ["/docker-entrypoint.sh"]
    ports:
      - "5177:5177"